### ISSUE TITLE
[MAP] Can't set rectangle ratio map in GridInfos.java

### ISSUE THREAD

**Issue by Juknum** [CyrilleStr/AP4B#4]
It's basically a square, but when you change the width to be a rectangle, the grid can't generate:
(it was working fine when firstly implemented)

![image](https://user-images.githubusercontent.com/49886317/145126185-2d567e26-64a6-4e24-aca4-c6338945c164.png)
![image](https://user-images.githubusercontent.com/49886317/145126241-badea968-cef3-4992-a804-2b70f00bd289.png)

**Comment by Nchrd** [comment]
Comme on est des dev incroyable, ce bug est évidemment fixed
